### ISSUE TITLE
Plugin Crashing Constantly

### ISSUE THREAD

**Issue by SteamingSugar** [caseif/TTT#21]
The plugin would keep kicking us out of the arena we joined. This was the error we got.
11.07 04:15:53 [Server] INFO Could not pass event MinigameRoundEndEvent to TTT v0.7.2

Then I restarted and as usual everytime I type /ttt it comes up with /ttt [subcommand](in white) and whatever I type as a sub command nothing works! This is one of the logs from the plugin after startup 
11.07 04:20:54 [Server] INFO at net.caseif.ttt.Main.onDisable(Main.java:305) ~[?:?]
11.07 04:20:54 [Server] INFO java.lang.NullPointerException
11.07 04:20:54 [Server] ERROR Error occurred while disabling TTT v0.7.2 (Is it up to date?)
11.07 04:20:54 [Server] WARN Default system encoding may have misread config.yml from plugin jar
11.07 04:20:54 [Server] INFO Disabling TTT v0.7.2

**Comment by caseif** [comment]
You'll need to provide a stack trace for me to determine what's going wrong (it's the part of the log that looks like nonsensical spam, but for good measure I'd suggest pasting the entire log regardless). Also, when you say you restarted, did you fully restart the server or just reload it? TTT doesn't handle reloads very well sometimes.

**Comment by SteamingSugar** [comment]
I will post a stack trace, I restarted the server I did not reload with another plugin (e.g Plugman)

**Comment by SteamingSugar** [comment]
```
14.07 03:23:22 [Multicraft] Received restart command
14.07 03:23:22 [Multicraft] Stopping server!
14.07 03:23:22 [Multicraft] Received restart command
14.07 03:23:22 [Server] INFO Stopping server
14.07 03:23:22 [Server] INFO Disabling TTT v0.7.2
14.07 03:23:22 [Server] WARN Default system encoding may have misread config.yml from plugin jar
14.07 03:23:22 [Server] ERROR Error occurred while disabling TTT v0.7.2 (Is it up to date?)
14.07 03:23:22 [Server] INFO java.lang.NullPointerException
14.07 03:23:22 [Server] INFO at net.caseif.ttt.Main.onDisable(Main.java:305) ~[?:?]
14.07 03:23:22 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:23:22 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:23:22 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins.jar:?]
```

Does that help?

**Comment by SteamingSugar** [comment]
Another thing:

```
14.07 03:41:42 [Server] INFO java.lang.NullPointerException
14.07 03:41:42 [Server] INFO at net.caseif.ttt.Main.onDisable(Main.java:305) ~[?:?]
14.07 03:41:42 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins.jar:?]
14.07 03:41:42 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.unload(PluginUtil.java:372) [PlugMan.jar:?]
14.07 03:41:42 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:298) [PlugMan.jar:?]
14.07 03:41:42 [Server] INFO at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) [PlugMan.jar:?]
14.07 03:41:42 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:104) [PlugMan.jar:?]
14.07 03:41:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at us.Myles.PWP.FakeSimpleCommandMap.dispatch(FakeSimpleCommandMap.java:95) [PerWorldPlugins.jar:?]
14.07 03:41:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchServerCommand(CraftServer.java:632) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.aM(DedicatedServer.java:353) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:317) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
14.07 03:41:42 [Server] INFO Enabling TTT v0.7.2
14.07 03:41:42 [Server] ERROR Error occurred while enabling TTT v0.7.2 (Is it up to date?)
14.07 03:41:42 [Server] INFO java.lang.IllegalStateException: TTT v0.7.2 attempted to hook into MGLib while an instance of the API was already registered. This is a bug, and should be reported this to the author(s) of the hooking plugin (Maxim Roncac�)
14.07 03:41:42 [Server] INFO at net.amigocraft.mglib.api.Minigame.(Minigame.java:88) ~[?:?]
14.07 03:41:42 [Server] INFO at net.amigocraft.mglib.api.Minigame.registerPlugin(Minigame.java:124) ~[?:?]
14.07 03:41:42 [Server] INFO at net.caseif.ttt.Main.onEnable(Main.java:120) ~[?:?]
14.07 03:41:42 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:42 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
14.07 03:41:43 [Multicraft] Skipped 16 lines due to rate limit (30/s)
```

**Comment by caseif** [comment]
Well... that's certainly interesting. I'll take a closer look a bit later to try to sort out exactly what's going wrong. How is the server being (re)started exactly btw, is anything out of the ordinary being done?

**Comment by SteamingSugar** [comment]
The server is being restarted via multicraft, nothing out of the ordinary
is going wrong. I MIGHT of restarted with plugman (can't remember) and then
did a full server restart.

Installing a new jar file hasn't helped

**Comment by caseif** [comment]
The reason for the second stack trace is that for some reason TTT is being started immediately after it's disabled, whereas normally all plugins would be disabled and only then would they be reinitialized. This causes issues with MGLib. I have no idea why that's happening, but I'll push a patch to MGLib to attempt to handle this type of situation. Check for `0.4.3-SNAPSHOT` on [ci.caseif.net](http://ci.caseif.net/job/MGLib).

**Comment by SteamingSugar** [comment]
This is still going on

```
[TTT] Disabling TTT v0.7.2
[02:02:43] [Server thread/WARN]: [TTT] Default system encoding may have misread config.yml from plugin jar
[02:02:43] [Server thread/ERROR]: Error occurred while disabling TTT v0.7.2 (Is it up to date?)
java.lang.NullPointerException
    at net.caseif.ttt.Main.onDisable(Main.java:305) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot_server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
    at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.disablePlugin(PerWorldPluginLoader.java:140) [PerWorldPlugins.jar:?]
    at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
    at org.bukkit.craftbukkit.v1_8_R1.CraftServer.disablePlugins(CraftServer.java:335) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.stop(MinecraftServer.java:441) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
    at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:572) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
```

**Comment by caseif** [comment]
This appears to be an incompatibility with [PerWorldPlugins](https://github.com/MylesIsCool/PerWorldPlugins/). As far as I can tell it shouldn't affect operation aside from the stack trace with MGLib now patched, but regardless, I'll continue looking into it. Would you mind running [this debug build](https://drive.google.com/file/d/0B8_nDMQp-qqCRmVRbk5Hd0RMSjQ/view?usp=sharing)?

**Comment by SteamingSugar** [comment]
I replaced current jar file with the debug build, doesn't work.

I removed the folder of TTT and jar file and put fresh ones. worked.

I removed the folder and put in the old one, so i could keep the arenas. stopped working

(While doing this I was stopping the server between file transfers)

**Comment by caseif** [comment]
What happens when you load the server with the debug build installed?

**Comment by SteamingSugar** [comment]
I put in the debug build while keeping the folder, didn't work and came up
with similar an error as before.

I took out the JAR file and the folder. Put the jar file again, and it
worked like normal. I then put the old folder back in and again it stopped
working. Similar error as first time

**Comment by caseif** [comment]
Could you please paste the output of the plugin when it throws an error?

**Comment by SteamingSugar** [comment]
I found this error getting spammed in console recently.

```
18.07 00:43:21 [Server] ERROR Could not pass event PlayerInteractEvent to MGLib v0.4.3-SNAPSHOT-git(master-9f53a7c)-jnks241
18.07 00:43:21 [Server] INFO org.bukkit.event.EventException
18.07 00:43:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:226) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerInteractManager.interact(PlayerInteractManager.java:463) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:724) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:50) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:80) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_71]
18.07 00:43:21 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_71]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:696) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
18.07 00:43:21 [Server] INFO Caused by: java.lang.NullPointerException
18.07 00:43:21 [Server] INFO at net.amigocraft.mglib.MGListener.onPlayerInteract(MGListener.java:778) ~[?:?]
18.07 00:43:21 [Server] INFO at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source) ~[?:?]
18.07 00:43:21 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_71]
18.07 00:43:21 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_71]
18.07 00:43:21 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot_server.jar:git-Spigot-c3c767f-33d5de3]
18.07 00:43:21 [Server] INFO ... 16 more
```

**Comment by caseif** [comment]
Most of those errors are coming from `HideAndCustomPlugins`, so you'll need to take those up with the author of that plugin. I've edited the log to only include the exception thrown by MGLib.

What happens when you attempt to restart the server, when TTT is diabled? Is an exception still thrown?

**Comment by SteamingSugar** [comment]
I fixed it, I replaced the jar file, cleared out karma etc and it worked:

Perworldplugins: 
Developers (You shouldn't need this v1.2.0+)

API: Currently we don't support one. If you want one, suggest the features you want! 

If your plugin is incompatible, it is mainly because the plugin might extend to SimplePluginManager. PerWorldPlugins will not extend to that class due to its protection; how can you expect us to do so without some more l33t hacky code manipulation? 

Here's an example on how to fix it: 

Before: (incompatible) 

SimplePluginManager spm = (SimplePluginManager)Bukkit.getServer().getPluginManager();
Field scmF = spm.getClass().getDeclaredField("commandMap");

After: (compatible!) 

PluginManager pm = Bukkit.getServer().getPluginManager();
Field scmF = pm.getClass().getDeclaredField("commandMap");

**Comment by caseif** [comment]
Glad to hear you fixed it.
