### ISSUE TITLE
I got an error at my 1.8-R0.1 Server

### ISSUE THREAD

**Issue by xXSchrandXx** [caseif/TTT#39]
Plugins: CleanroomGenerator, Clearlag, Essentials, EssentialsChat, iConemy, InfoboardReborn, Multiverse-Core, NametagEdit, PermissionsEx, Steel, TagAPI, TeleportSigns, TTT, Vault, worldedit, worldguard and my Plugin for Bungee.

It comes when I set the Spawnpoint for the players with "OK".

[23:04:35] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to TTT v0.9.6
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[craftbukkit.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.PlayerConnection.chat(PlayerConnection.java:1036) [craftbukkit.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:975) [craftbukkit.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26) [craftbukkit.jar:git-Spigot-550ebac-7019900]
    at net.minecraft.server.v1_8_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:47) [craftbukkit.jar:git-Spigot-550ebac-7019900]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_80]
    at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_80]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_80]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_80]
    at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.NoClassDefFoundError: com/google/gson/JsonParser
    at net.caseif.flint.common.util.helper.rollback.CommonRollbackHelper.initializeStateStore(CommonRollbackHelper.java:350) ~[?:?]
    at net.caseif.flint.common.util.helper.rollback.CommonRollbackHelper.<init>(CommonRollbackHelper.java:74) ~[?:?]
    at net.caseif.flint.steel.util.helper.rollback.RollbackHelper.<init>(RollbackHelper.java:70) ~[?:?]
    at net.caseif.flint.steel.arena.SteelArena.<init>(SteelArena.java:88) ~[?:?]
    at net.caseif.flint.steel.minigame.SteelMinigame.createArena(SteelMinigame.java:99) ~[?:?]
    at net.caseif.flint.steel.minigame.SteelMinigame.createArena(SteelMinigame.java:112) ~[?:?]
    at net.caseif.ttt.listeners.WizardListener.onAsyncPlayerChat(WizardListener.java:122) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit.jar:git-Spigot-550ebac-7019900]
    ... 12 more
Caused by: java.lang.ClassNotFoundException: com.google.gson.JsonParser
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.7.0_80]
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_80]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_80]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-550ebac-7019900]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-550ebac-7019900]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
    at net.caseif.flint.common.util.helper.rollback.CommonRollbackHelper.initializeStateStore(CommonRollbackHelper.java:350) ~[?:?]
    at net.caseif.flint.common.util.helper.rollback.CommonRollbackHelper.<init>(CommonRollbackHelper.java:74) ~[?:?]
    at net.caseif.flint.steel.util.helper.rollback.RollbackHelper.<init>(RollbackHelper.java:70) ~[?:?]
    at net.caseif.flint.steel.arena.SteelArena.<init>(SteelArena.java:88) ~[?:?]
    at net.caseif.flint.steel.minigame.SteelMinigame.createArena(SteelMinigame.java:99) ~[?:?]
    at net.caseif.flint.steel.minigame.SteelMinigame.createArena(SteelMinigame.java:112) ~[?:?]
    at net.caseif.ttt.listeners.WizardListener.onAsyncPlayerChat(WizardListener.java:122) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[craftbukkit.jar:git-Spigot-550ebac-7019900]
    ... 12 more

**Comment by caseif** [comment]
What is the full output of the `/version` command?

**Comment by caseif** [comment]
I'll investigate this when I next get a chance.

**Comment by xXSchrandXx** [comment]
Verion: This server is running CraftBukkit version git-Spigot-550ebac-7019900 (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by caseif** [comment]
Your Spigot revision seems to be very old. Could you try to reproduce on the latest 1.8 build (git-e4d4710)?

**Comment by xXSchrandXx** [comment]
ok, thank you for the help

**Comment by caseif** [comment]
Were you able to reproduce the issue?

**Comment by xXSchrandXx** [comment]
It works now, no errors or bugs. Thank you

**Comment by xXSchrandXx** [comment]
Do the spectator normaly spawn in gamemode 3?

Because user with '*' permissions getting in Gamemode 3 and the other in Gamemode 0.

**Comment by caseif** [comment]
Yes, they do. If they aren't, it's likely the result of a conflict with another plugin. Try systematically disabling them to see if you can determine which one.
